[program:lp_api]
command=/root/doma-automation/venv/bin/uvicorn api:app --host 0.0.0.0 --port 5002 --log-level info
directory=/root/doma-automation/lp-bot
autostart=true
autorestart=true
stderr_logfile=/var/log/lp_api.err.log
stdout_logfile=/var/log/lp_api.out.log
user=root
stopsignal=INT
stopwaitsecs=10
environment=PYTHONUNBUFFERED="1"
