[program:lp_bot]
command=/root/doma-automation/venv/bin/python3 /root/doma-automation/lp-bot/lp_bot.py
directory=/root/doma-automation/lp-bot
autostart=true
autorestart=true
stderr_logfile=/var/log/lp_bot.err.log
stdout_logfile=/var/log/lp_bot.out.log
user=root
stopsignal=INT
stopwaitsecs=10
